// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  biography: dynamic(() => import("./Biography")),
  content_index: dynamic(() => import("./ContentIndex")),
  homepage: dynamic(() => import("./Homepage")),
  tech_list: dynamic(() => import("./TechList")),
  text_blog: dynamic(() => import("./TextBlog")),
};
